apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: faelivrinx/keycloak
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_ADDR
              value: "192.168.99.1:5432"
            - name: DB_DATABASE
              value: "key_db"
            - name: DB_USER
              value: "key_user"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_PASSWORD
              value: "key_password"
            - name: INFLUXDB_HOST
              value: "192.168.99.1"
            - name: INFLUXDB_PORT
              value: "8086"
            - name: INFLUXDB_USER
              value: "root"
            - name: INFLUXDB_PWD
              value: "root"
            - name: INFLUXDB_DB
              value: "keycloak"
